parameters:
    fungio.dataexporter.class: Fungio\DataExporterBundle\Service\DataExporter

services:
    fungio.dataexporter:
        class: %fungio.dataexporter.class%
        public: true
        scope: prototype
